name: Rust

on:
  push:
    branches: [ "ci-1" ]
  pull_request:
    branches: [ "ci-1" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update; sudo apt-get install --no-install-recommends clang
    - name: compile mold
      run: |
        git clone https://github.com/rui314/mold.git
        mkdir mold/build
        cd mold/build
        git checkout v1.6.0
        sudo ../install-build-deps.sh
        sudo cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=c++ ..
        sudo cmake --build . -j $(nproc)
        sudo cmake --install .
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
