name: Rust

on:
  push:
    branches: [ "ci-1" ]
  pull_request:
    branches: [ "ci-1" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update; sudo apt-get install clang
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
